# environment variable config map
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "frontend.fullname" . }}
  labels: {{- include "frontend.labels" . | nindent 4 }}
data:
  {{- range .Values.env }}
  {{ .name }}: {{ .value | quote }}
  {{- end }}
