"""Update unit table

Revision ID: 49f3d805cae9
Revises: a95b6d19f516
Create Date: 2024-08-13 17:28:51.234124

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '49f3d805cae9'
down_revision: Union[str, None] = 'a95b6d19f516'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('unit', sa.Column('name', sa.String(), nullable=False))
    op.add_column('unit', sa.Column('symbol', sa.String(), nullable=True))
    op.create_index(op.f('ix_unit_name'), 'unit', ['name'], unique=False)
    op.create_index(op.f('ix_unit_symbol'), 'unit', ['symbol'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_unit_symbol'), table_name='unit')
    op.drop_index(op.f('ix_unit_name'), table_name='unit')
    op.drop_column('unit', 'symbol')
    op.drop_column('unit', 'name')
    # ### end Alembic commands ###
