"""Update keys

Revision ID: 5d857111e5a9
Revises: e7140aede8b5
Create Date: 2024-07-26 20:20:04.444469

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5d857111e5a9'
down_revision: Union[str, None] = 'e7140aede8b5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('managednutrientcategoryoverride', 'id')
    op.drop_column('managednutrientoverride', 'id')
    op.add_column('nutrient', sa.Column('organization_id', sa.String(), nullable=True))
    op.alter_column('nutrient', 'nutrient_category_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_foreign_key(None, 'nutrient', 'organization', ['organization_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'nutrient', type_='foreignkey')
    op.alter_column('nutrient', 'nutrient_category_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('nutrient', 'organization_id')
    op.add_column('managednutrientoverride', sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.add_column('managednutrientcategoryoverride', sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False))
    # ### end Alembic commands ###
