"""Add ingredient-nutrient join table

Revision ID: 704f7b37cbc4
Revises: ea2e475d225a
Create Date: 2024-07-31 21:12:04.536416

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '704f7b37cbc4'
down_revision: Union[str, None] = 'ea2e475d225a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ingredientnutrient',
    sa.Column('ingredient_id', sa.Integer(), nullable=False),
    sa.Column('nutrient_id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.String(), nullable=False),
    sa.Column('archived', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['ingredient_id'], ['ingredient.id'], ),
    sa.ForeignKeyConstraint(['nutrient_id'], ['nutrient.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], ),
    sa.PrimaryKeyConstraint('ingredient_id', 'nutrient_id', 'organization_id')
    )
    op.create_index(op.f('ix_ingredientnutrient_archived'), 'ingredientnutrient', ['archived'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ingredientnutrient_archived'), table_name='ingredientnutrient')
    op.drop_table('ingredientnutrient')
    # ### end Alembic commands ###
