"""Add units to nutrient value table

Revision ID: 8004bb11e498
Revises: c5a17883e285
Create Date: 2024-08-15 20:32:37.693347

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8004bb11e498'
down_revision: Union[str, None] = 'c5a17883e285'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profilenutrientvalue', sa.Column('gross_energy_unit_id', sa.String(), nullable=True))
    op.add_column('profilenutrientvalue', sa.Column('digestible_energy_unit_id', sa.String(), nullable=True))
    op.add_column('profilenutrientvalue', sa.Column('metabolizable_energy_unit_id', sa.String(), nullable=True))
    op.add_column('profilenutrientvalue', sa.Column('net_energy_unit_id', sa.String(), nullable=True))
    op.create_foreign_key(None, 'profilenutrientvalue', 'unit', ['metabolizable_energy_unit_id'], ['id'])
    op.create_foreign_key(None, 'profilenutrientvalue', 'unit', ['gross_energy_unit_id'], ['id'])
    op.create_foreign_key(None, 'profilenutrientvalue', 'unit', ['net_energy_unit_id'], ['id'])
    op.create_foreign_key(None, 'profilenutrientvalue', 'unit', ['digestible_energy_unit_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'profilenutrientvalue', type_='foreignkey')
    op.drop_constraint(None, 'profilenutrientvalue', type_='foreignkey')
    op.drop_constraint(None, 'profilenutrientvalue', type_='foreignkey')
    op.drop_constraint(None, 'profilenutrientvalue', type_='foreignkey')
    op.drop_column('profilenutrientvalue', 'net_energy_unit_id')
    op.drop_column('profilenutrientvalue', 'metabolizable_energy_unit_id')
    op.drop_column('profilenutrientvalue', 'digestible_energy_unit_id')
    op.drop_column('profilenutrientvalue', 'gross_energy_unit_id')
    # ### end Alembic commands ###
