"""Add ingredients

Revision ID: 887768219df7
Revises: 5d857111e5a9
Create Date: 2024-07-30 20:07:31.753719

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '887768219df7'
down_revision: Union[str, None] = '5d857111e5a9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ingredientcategory',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.String(), nullable=True),
    sa.Column('parent_ingredient_category_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('managed', sa.Boolean(), nullable=False),
    sa.Column('archived', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], ),
    sa.ForeignKeyConstraint(['parent_ingredient_category_id'], ['ingredientcategory.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ingredientcategory_archived'), 'ingredientcategory', ['archived'], unique=False)
    op.create_index(op.f('ix_ingredientcategory_name'), 'ingredientcategory', ['name'], unique=False)
    op.create_table('ingredient',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.String(), nullable=True),
    sa.Column('ingredient_category_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('managed', sa.Boolean(), nullable=False),
    sa.Column('archived', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['ingredient_category_id'], ['ingredientcategory.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ingredient_archived'), 'ingredient', ['archived'], unique=False)
    op.create_index(op.f('ix_ingredient_name'), 'ingredient', ['name'], unique=False)
    op.create_table('managedingredientcategoryoverride',
    sa.Column('organization_id', sa.String(), nullable=False),
    sa.Column('ingredient_category_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('archived', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['ingredient_category_id'], ['ingredientcategory.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], ),
    sa.PrimaryKeyConstraint('organization_id', 'ingredient_category_id')
    )
    op.create_index(op.f('ix_managedingredientcategoryoverride_archived'), 'managedingredientcategoryoverride', ['archived'], unique=False)
    op.create_index(op.f('ix_managedingredientcategoryoverride_name'), 'managedingredientcategoryoverride', ['name'], unique=False)
    op.create_table('managedingredientoverride',
    sa.Column('organization_id', sa.String(), nullable=False),
    sa.Column('ingredient_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('archived', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['ingredient_id'], ['ingredient.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], ),
    sa.PrimaryKeyConstraint('organization_id', 'ingredient_id')
    )
    op.create_index(op.f('ix_managedingredientoverride_archived'), 'managedingredientoverride', ['archived'], unique=False)
    op.create_index(op.f('ix_managedingredientoverride_name'), 'managedingredientoverride', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_managedingredientoverride_name'), table_name='managedingredientoverride')
    op.drop_index(op.f('ix_managedingredientoverride_archived'), table_name='managedingredientoverride')
    op.drop_table('managedingredientoverride')
    op.drop_index(op.f('ix_managedingredientcategoryoverride_name'), table_name='managedingredientcategoryoverride')
    op.drop_index(op.f('ix_managedingredientcategoryoverride_archived'), table_name='managedingredientcategoryoverride')
    op.drop_table('managedingredientcategoryoverride')
    op.drop_index(op.f('ix_ingredient_name'), table_name='ingredient')
    op.drop_index(op.f('ix_ingredient_archived'), table_name='ingredient')
    op.drop_table('ingredient')
    op.drop_index(op.f('ix_ingredientcategory_name'), table_name='ingredientcategory')
    op.drop_index(op.f('ix_ingredientcategory_archived'), table_name='ingredientcategory')
    op.drop_table('ingredientcategory')
    # ### end Alembic commands ###
