"""Add diet output tables

Revision ID: 986932df18bd
Revises: 2407e2cea5ec
Create Date: 2024-08-24 18:21:02.545298

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '986932df18bd'
down_revision: Union[str, None] = '2407e2cea5ec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dietingredientoutput', sa.Column('gross_energy', sa.Float(), nullable=True))
    op.add_column('dietingredientoutput', sa.Column('gross_energy_unit_id', sa.String(), nullable=True))
    op.add_column('dietingredientoutput', sa.Column('digestible_energy', sa.Float(), nullable=True))
    op.add_column('dietingredientoutput', sa.Column('digestible_energy_unit_id', sa.String(), nullable=True))
    op.add_column('dietingredientoutput', sa.Column('metabolizable_energy', sa.Float(), nullable=True))
    op.add_column('dietingredientoutput', sa.Column('metabolizable_energy_unit_id', sa.String(), nullable=True))
    op.add_column('dietingredientoutput', sa.Column('net_energy', sa.Float(), nullable=True))
    op.add_column('dietingredientoutput', sa.Column('net_energy_unit_id', sa.String(), nullable=True))
    op.create_foreign_key(None, 'dietingredientoutput', 'unit', ['net_energy_unit_id'], ['id'])
    op.create_foreign_key(None, 'dietingredientoutput', 'unit', ['metabolizable_energy_unit_id'], ['id'])
    op.create_foreign_key(None, 'dietingredientoutput', 'unit', ['digestible_energy_unit_id'], ['id'])
    op.create_foreign_key(None, 'dietingredientoutput', 'unit', ['gross_energy_unit_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'dietingredientoutput', type_='foreignkey')
    op.drop_constraint(None, 'dietingredientoutput', type_='foreignkey')
    op.drop_constraint(None, 'dietingredientoutput', type_='foreignkey')
    op.drop_constraint(None, 'dietingredientoutput', type_='foreignkey')
    op.drop_column('dietingredientoutput', 'net_energy_unit_id')
    op.drop_column('dietingredientoutput', 'net_energy')
    op.drop_column('dietingredientoutput', 'metabolizable_energy_unit_id')
    op.drop_column('dietingredientoutput', 'metabolizable_energy')
    op.drop_column('dietingredientoutput', 'digestible_energy_unit_id')
    op.drop_column('dietingredientoutput', 'digestible_energy')
    op.drop_column('dietingredientoutput', 'gross_energy_unit_id')
    op.drop_column('dietingredientoutput', 'gross_energy')
    # ### end Alembic commands ###
