"""Do stuff

Revision ID: a95b6d19f516
Revises: 3bf1ecd7a259
Create Date: 2024-08-11 18:31:35.549757

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a95b6d19f516'
down_revision: Union[str, None] = '3bf1ecd7a259'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('profile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.String(), nullable=True),
    sa.Column('managed', sa.Boolean(), nullable=False),
    sa.Column('managed_key', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('archived', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_profile_archived'), 'profile', ['archived'], unique=False)
    op.create_index(op.f('ix_profile_managed_key'), 'profile', ['managed_key'], unique=False)
    op.create_index(op.f('ix_profile_name'), 'profile', ['name'], unique=False)
    op.create_table('profileconstraint',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('archived', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['profile.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_profileconstraint_archived'), 'profileconstraint', ['archived'], unique=False)
    op.create_table('profilepandalistrule',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('scope', sa.String(), nullable=False),
    sa.Column('mode', sa.String(), nullable=False),
    sa.Column('archived', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['profile.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_profilepandalistrule_archived'), 'profilepandalistrule', ['archived'], unique=False)
    op.create_table('profileingredientconstraint',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('ingredient_id', sa.Integer(), nullable=False),
    sa.Column('mode', sa.String(), nullable=False),
    sa.Column('operator', sa.String(), nullable=False),
    sa.Column('literal_unit_id', sa.String(), nullable=True),
    sa.Column('literal_value', sa.Float(), nullable=True),
    sa.Column('reference_ingredient_id', sa.Integer(), nullable=True),
    sa.Column('archived', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['ingredient_id'], ['ingredient.id'], ),
    sa.ForeignKeyConstraint(['literal_unit_id'], ['unit.id'], ),
    sa.ForeignKeyConstraint(['profile_id'], ['profile.id'], ),
    sa.ForeignKeyConstraint(['reference_ingredient_id'], ['ingredient.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_profileingredientconstraint_archived'), 'profileingredientconstraint', ['archived'], unique=False)
    op.create_table('profileingredientnutrientvalue',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('ingredient_id', sa.Integer(), nullable=False),
    sa.Column('nutrient_id', sa.Integer(), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('unit_id', sa.String(), nullable=False),
    sa.Column('archived', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['ingredient_id'], ['ingredient.id'], ),
    sa.ForeignKeyConstraint(['nutrient_id'], ['nutrient.id'], ),
    sa.ForeignKeyConstraint(['profile_id'], ['profile.id'], ),
    sa.ForeignKeyConstraint(['unit_id'], ['unit.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_profileingredientnutrientvalue_archived'), 'profileingredientnutrientvalue', ['archived'], unique=False)
    op.create_table('profilenutrientconstraint',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('nutrient_id', sa.Integer(), nullable=False),
    sa.Column('mode', sa.String(), nullable=False),
    sa.Column('operator', sa.String(), nullable=False),
    sa.Column('literal_unit_id', sa.String(), nullable=True),
    sa.Column('literal_value', sa.Float(), nullable=True),
    sa.Column('reference_nutrient_id', sa.Integer(), nullable=True),
    sa.Column('archived', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['literal_unit_id'], ['unit.id'], ),
    sa.ForeignKeyConstraint(['nutrient_id'], ['nutrient.id'], ),
    sa.ForeignKeyConstraint(['profile_id'], ['profile.id'], ),
    sa.ForeignKeyConstraint(['reference_nutrient_id'], ['nutrient.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_profilenutrientconstraint_archived'), 'profilenutrientconstraint', ['archived'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_profilenutrientconstraint_archived'), table_name='profilenutrientconstraint')
    op.drop_table('profilenutrientconstraint')
    op.drop_index(op.f('ix_profileingredientnutrientvalue_archived'), table_name='profileingredientnutrientvalue')
    op.drop_table('profileingredientnutrientvalue')
    op.drop_index(op.f('ix_profileingredientconstraint_archived'), table_name='profileingredientconstraint')
    op.drop_table('profileingredientconstraint')
    op.drop_index(op.f('ix_profilepandalistrule_archived'), table_name='profilepandalistrule')
    op.drop_table('profilepandalistrule')
    op.drop_index(op.f('ix_profileconstraint_archived'), table_name='profileconstraint')
    op.drop_table('profileconstraint')
    op.drop_index(op.f('ix_profile_name'), table_name='profile')
    op.drop_index(op.f('ix_profile_managed_key'), table_name='profile')
    op.drop_index(op.f('ix_profile_archived'), table_name='profile')
    op.drop_table('profile')
    # ### end Alembic commands ###
