"""Update unit table

Revision ID: d53e656f50fe
Revises: 8004bb11e498
Create Date: 2024-08-15 21:06:52.243206

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d53e656f50fe"
down_revision: Union[str, None] = "8004bb11e498"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("unit", sa.Column("type", sa.String(), nullable=False))
    op.create_index(op.f("ix_unit_type"), "unit", ["type"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "unit",
        sa.Column(
            "kilogram_multiplier",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.add_column(
        "unit",
        sa.Column(
            "kilogram_offset",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.drop_index(op.f("ix_unit_type"), table_name="unit")
    op.drop_column("unit", "base_unit_offset")
    op.drop_column("unit", "base_unit_multiplier")
    op.drop_column("unit", "type")
    # ### end Alembic commands ###
