"""Initial revision

Revision ID: e7140aede8b5
Revises: 
Create Date: 2024-07-20 21:56:45.804850

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e7140aede8b5'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organization',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('archived', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_organization_archived'), 'organization', ['archived'], unique=False)
    op.create_table('user',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('archived', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_archived'), 'user', ['archived'], unique=False)
    op.create_table('nutrientcategory',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.String(), nullable=True),
    sa.Column('parent_nutrient_category_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('managed', sa.Boolean(), nullable=False),
    sa.Column('archived', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], ),
    sa.ForeignKeyConstraint(['parent_nutrient_category_id'], ['nutrientcategory.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_nutrientcategory_archived'), 'nutrientcategory', ['archived'], unique=False)
    op.create_index(op.f('ix_nutrientcategory_name'), 'nutrientcategory', ['name'], unique=False)
    op.create_table('organizationmembership',
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('organization_id', sa.String(), nullable=False),
    sa.Column('archived', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'organization_id')
    )
    op.create_index(op.f('ix_organizationmembership_archived'), 'organizationmembership', ['archived'], unique=False)
    op.create_table('managednutrientcategoryoverride',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nutrient_category_id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('archived', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['nutrient_category_id'], ['nutrientcategory.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_managednutrientcategoryoverride_archived'), 'managednutrientcategoryoverride', ['archived'], unique=False)
    op.create_index(op.f('ix_managednutrientcategoryoverride_name'), 'managednutrientcategoryoverride', ['name'], unique=False)
    op.create_table('nutrient',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nutrient_category_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('managed', sa.Boolean(), nullable=False),
    sa.Column('archived', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['nutrient_category_id'], ['nutrientcategory.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_nutrient_archived'), 'nutrient', ['archived'], unique=False)
    op.create_index(op.f('ix_nutrient_name'), 'nutrient', ['name'], unique=False)
    op.create_table('managednutrientoverride',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nutrient_id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('archived', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['nutrient_id'], ['nutrient.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_managednutrientoverride_archived'), 'managednutrientoverride', ['archived'], unique=False)
    op.create_index(op.f('ix_managednutrientoverride_name'), 'managednutrientoverride', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_managednutrientoverride_name'), table_name='managednutrientoverride')
    op.drop_index(op.f('ix_managednutrientoverride_archived'), table_name='managednutrientoverride')
    op.drop_table('managednutrientoverride')
    op.drop_index(op.f('ix_nutrient_name'), table_name='nutrient')
    op.drop_index(op.f('ix_nutrient_archived'), table_name='nutrient')
    op.drop_table('nutrient')
    op.drop_index(op.f('ix_managednutrientcategoryoverride_name'), table_name='managednutrientcategoryoverride')
    op.drop_index(op.f('ix_managednutrientcategoryoverride_archived'), table_name='managednutrientcategoryoverride')
    op.drop_table('managednutrientcategoryoverride')
    op.drop_index(op.f('ix_organizationmembership_archived'), table_name='organizationmembership')
    op.drop_table('organizationmembership')
    op.drop_index(op.f('ix_nutrientcategory_name'), table_name='nutrientcategory')
    op.drop_index(op.f('ix_nutrientcategory_archived'), table_name='nutrientcategory')
    op.drop_table('nutrientcategory')
    op.drop_index(op.f('ix_user_archived'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_organization_archived'), table_name='organization')
    op.drop_table('organization')
    # ### end Alembic commands ###
