"""Add managed key

Revision ID: ea2e475d225a
Revises: 887768219df7
Create Date: 2024-07-31 20:21:46.665459

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ea2e475d225a'
down_revision: Union[str, None] = '887768219df7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ingredient', sa.Column('managed_key', sa.String(), nullable=True))
    op.create_index(op.f('ix_ingredient_managed_key'), 'ingredient', ['managed_key'], unique=False)
    op.add_column('ingredientcategory', sa.Column('managed_key', sa.String(), nullable=True))
    op.create_index(op.f('ix_ingredientcategory_managed_key'), 'ingredientcategory', ['managed_key'], unique=False)
    op.add_column('nutrient', sa.Column('managed_key', sa.String(), nullable=True))
    op.create_index(op.f('ix_nutrient_managed_key'), 'nutrient', ['managed_key'], unique=False)
    op.add_column('nutrientcategory', sa.Column('managed_key', sa.String(), nullable=True))
    op.create_index(op.f('ix_nutrientcategory_managed_key'), 'nutrientcategory', ['managed_key'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_nutrientcategory_managed_key'), table_name='nutrientcategory')
    op.drop_column('nutrientcategory', 'managed_key')
    op.drop_index(op.f('ix_nutrient_managed_key'), table_name='nutrient')
    op.drop_column('nutrient', 'managed_key')
    op.drop_index(op.f('ix_ingredientcategory_managed_key'), table_name='ingredientcategory')
    op.drop_column('ingredientcategory', 'managed_key')
    op.drop_index(op.f('ix_ingredient_managed_key'), table_name='ingredient')
    op.drop_column('ingredient', 'managed_key')
    # ### end Alembic commands ###
