{{- if .Values.httpRoute.enabled -}}
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ include "backend.fullname" . }}
  labels:
    {{- include "backend.labels" . | nindent 4 }}
spec:
  parentRefs:
  - name: {{ .Values.httpRoute.gateway }}
  hostnames: {{ .Values.httpRoute.hostnames | toJson }}
  rules:
  {{- range .Values.httpRoute.match }}
  - matches:
    - path:
        type: PathPrefix
        value: {{ .path }}
    filters:
      - type: URLRewrite
        urlRewrite:
          path:
            type: ReplacePrefixMatch
            replacePrefixMatch: {{ .servicePath }}
  {{- end }}
    backendRefs:
    - name: {{ include "backend.fullname" . }}
      port: {{ .Values.service.port }}
{{- end -}}