name: deploy-istio
run-name: Deploy Istio
concurrency:
  group: istio
  cancel-in-progress: true
  timeout-minutes: 60
on:
  push:
    paths:
      - "infra/istio/**"
    branches:
      - main
jobs:
  deploy-istio:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install Helm
        uses: azure/setup-helm@v4.2.0
        with:
          version: latest
        id: install_helm
      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      - name: Save DigitalOcean kubeconfig
        run: doctl kubernetes cluster kubeconfig save bc413b3b-f47f-433b-b166-b1ce40130b23
      - name: Install Istio
        run: |
          ./infra/istio/install.sh
