name: deploy-infra
run-name: Deploy Infra
concurrency:
  group: infra
  cancel-in-progress: true
on:
  push:
    paths:
      - "infra/infra/**"
      - "infra/chart/**"
      - ".github/workflows/deploy-infra.yaml"
    branches:
      - main
  workflow_dispatch:
    # only repo admins can run this workflow manually
    permissions:
      users: ["reecejones"]
jobs:
  deploy-infra:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install Helm
        uses: azure/setup-helm@v4.2.0
        with:
          version: latest
        id: install_helm
      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      - name: Save DigitalOcean kubeconfig
        run: doctl kubernetes cluster kubeconfig save ${{ secrets.DIGITALOCEAN_K8S_CLUSTER_ID }}
      - name: Install Infrastructure Chart
        run: |
          ./infra/infra/deploy.sh
